version: '3.8'

networks:
  power_net:
    driver: bridge

services:
  # 1. Database Service (TimescaleDB)
  db:
    image: timescale/timescaledb:latest-pg15
    container_name: power_monitoring_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: power_monitoring
      TZ: Asia/Tehran
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro # همگام‌سازی دقیق ساعت با سرور میزبان
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d power_monitoring"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - power_net

  # 2. Redis Broker Service
  redis:
    image: redis:alpine
    container_name: redis_broker
    restart: unless-stopped
    environment:
      TZ: Asia/Tehran
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - power_net

  api:
    build:
      context: .
      dockerfile: ./main_api/Dockerfile
    container_name: power_monitoring_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:admin@db:5432/power_monitoring
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: your_super_secret_key
      TZ: Asia/Tehran
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - power_net
  # 4. Telemetry Service (Modbus Reader)
  telemetry:
    build:
      context: ./telemetry_service
    container_name: power_monitoring_telemetry
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:admin@db:5432/power_monitoring
      REDIS_URL: redis://redis:6379/0
      POLLING_INTERVAL: 5
      MAX_TELEMETRY_FAILURES: 3
      TZ: Asia/Tehran
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - power_net

  # --- OPTIONAL: PgAdmin for Database Management ---
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: power_monitoring_pgadmin
  #   restart: unless-stopped
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - db
  #   networks:
  #     - power_net

volumes:
  postgres_data: