"""remove_unique_constraint_from_post_ip

Revision ID: 48b76a4b54ac
Revises: 088d59b31213
Create Date: 2026-08-22 15:03:14.400951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48b76a4b54ac'
down_revision: Union[str, Sequence[str], None] = '088d59b31213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('posts_ip_address_key'), 'posts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('posts_ip_address_key'), 'posts', ['ip_address'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
