"""add notif

Revision ID: 6ffcec25a133
Revises: 48b76a4b54ac
Create Date: 2026-09-14 09:27:24.451759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ffcec25a133'
down_revision: Union[str, Sequence[str], None] = '48b76a4b54ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('audit_logs', 'resource_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('audit_logs', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('audit_logs', 'changes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('audit_logs', 'error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_index(op.f('idx_audit_action'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_resource'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_user'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.alter_column('command_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.alter_column('command_logs', 'target',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('command_logs', 'parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('command_logs', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('command_logs', 'response',
                    existing_type=sa.TEXT(),
                    type_=sa.JSON(),
                    existing_nullable=True,
                    postgresql_using='response::json')

    op.alter_column('command_logs', 'response_time_ms',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('command_logs', 'error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_index(op.f('idx_command_post'), table_name='command_logs')
    op.drop_index(op.f('idx_command_success'), table_name='command_logs')
    op.drop_index(op.f('idx_command_timestamp'), table_name='command_logs')
    op.drop_index(op.f('idx_command_user'), table_name='command_logs')
    op.create_index(op.f('ix_command_logs_command_type'), 'command_logs', ['command_type'], unique=False)
    op.create_index(op.f('ix_command_logs_success'), 'command_logs', ['success'], unique=False)
    op.create_index(op.f('ix_command_logs_user_id'), 'command_logs', ['user_id'], unique=False)
    op.alter_column('device_test_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.alter_column('device_test_logs', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('device_test_logs', 'response_time_ms',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('device_test_logs', 'error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)

    op.create_index(op.f('ix_device_test_logs_test_type'), 'device_test_logs', ['test_type'], unique=False)
    op.add_column('users', sa.Column('sms_notification_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sms_notification_enabled')
    op.drop_index(op.f('ix_device_test_logs_test_type'), table_name='device_test_logs')
    op.alter_column('device_test_logs', 'error_message',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('device_test_logs', 'response_time_ms',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('device_test_logs', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('device_test_logs', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_command_logs_user_id'), table_name='command_logs')
    op.drop_index(op.f('ix_command_logs_success'), table_name='command_logs')
    op.drop_index(op.f('ix_command_logs_command_type'), table_name='command_logs')
    op.create_index(op.f('idx_command_user'), 'command_logs', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('idx_command_timestamp'), 'command_logs', ['timestamp'], unique=False)
    op.create_index(op.f('idx_command_success'), 'command_logs', ['success', 'timestamp'], unique=False)
    op.create_index(op.f('idx_command_post'), 'command_logs', ['post_id', 'timestamp'], unique=False)
    op.alter_column('command_logs', 'error_message',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('command_logs', 'response_time_ms',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # در تابع downgrade
    op.alter_column('command_logs', 'response',
                    existing_type=sa.JSON(),
                    type_=sa.TEXT(),
                    existing_nullable=True,
                    postgresql_using='response::text')

    op.alter_column('command_logs', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('command_logs', 'parameters',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('command_logs', 'target',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('command_logs', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.create_index(op.f('idx_audit_user'), 'audit_logs', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('idx_audit_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('idx_audit_resource'), 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('idx_audit_action'), 'audit_logs', ['action', 'timestamp'], unique=False)
    op.alter_column('audit_logs', 'error_message',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('audit_logs', 'meta_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'changes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'resource_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
