"""change setting fields

Revision ID: c464948a264d
Revises: 6ffcec25a133
Create Date: 2026-09-14 09:51:32.356549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c464948a264d'
down_revision: Union[str, Sequence[str], None] = '6ffcec25a133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'audit_log_retention_days')
    op.drop_column('system_settings', 'notification_batch_size')
    op.drop_column('system_settings', 'log_retention_days')
    op.drop_column('system_settings', 'maintenance_mode')
    op.drop_column('system_settings', 'refresh_token_expire_days')
    op.drop_column('system_settings', 'connection_pool_size')
    op.drop_column('system_settings', 'data_retention_days')
    op.drop_column('system_settings', 'system_name')
    op.drop_column('system_settings', 'system_timezone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('system_timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='منطقه زمانی'))
    op.add_column('system_settings', sa.Column('system_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='نام سیستم'))
    op.add_column('system_settings', sa.Column('data_retention_days', sa.INTEGER(), autoincrement=False, nullable=False, comment='مدت نگهداری داده\u200cهای تله\u200cمتری (روز)'))
    op.add_column('system_settings', sa.Column('connection_pool_size', sa.INTEGER(), autoincrement=False, nullable=False, comment='اندازه Pool اتصالات'))
    op.add_column('system_settings', sa.Column('refresh_token_expire_days', sa.INTEGER(), autoincrement=False, nullable=False, comment='مدت اعتبار Refresh Token (روز)'))
    op.add_column('system_settings', sa.Column('maintenance_mode', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='وضعیت تعمیر و نگهداری'))
    op.add_column('system_settings', sa.Column('log_retention_days', sa.INTEGER(), autoincrement=False, nullable=False, comment='مدت نگهداری لاگ\u200cها (روز)'))
    op.add_column('system_settings', sa.Column('notification_batch_size', sa.INTEGER(), autoincrement=False, nullable=False, comment='تعداد نوتیفیکیشن در هر Batch'))
    op.add_column('system_settings', sa.Column('audit_log_retention_days', sa.INTEGER(), autoincrement=False, nullable=False, comment='مدت نگهداری لاگ\u200cهای Audit (روز)'))
    # ### end Alembic commands ###
