"""add post_id and value_int to timeseries_data

Revision ID: d1651ca94c90
Revises: b6a97b729ebf
Create Date: 2026-08-20 12:50:00.855715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1651ca94c90'
down_revision: Union[str, Sequence[str], None] = 'b6a97b729ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_notification_preferences_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_expires_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_source_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_templates_id'), table_name='notification_templates')
    op.drop_index(op.f('ix_notification_templates_name'), table_name='notification_templates')
    op.drop_table('notification_templates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.ENUM('INFO', 'WARNING', 'ERROR', 'SUCCESS', 'ALERT', name='notificationtype'), autoincrement=False, nullable=False),
    sa.Column('priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='notificationpriority'), autoincrement=False, nullable=False),
    sa.Column('title_template', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message_template', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_templates_pkey'))
    )
    op.create_index(op.f('ix_notification_templates_name'), 'notification_templates', ['name'], unique=True)
    op.create_index(op.f('ix_notification_templates_id'), 'notification_templates', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('INFO', 'WARNING', 'ERROR', 'SUCCESS', 'ALERT', name='notificationtype'), autoincrement=False, nullable=False),
    sa.Column('priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='notificationpriority'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_dismissed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('dismissed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('action_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_source_type'), 'notifications', ['source_type'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_expires_at'), 'notifications', ['expires_at'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('enable_info', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('enable_warning', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('enable_error', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('enable_success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('enable_alert', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('min_priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='notificationpriority'), autoincrement=False, nullable=False),
    sa.Column('auto_dismiss_after_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('auto_dismiss_delay_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_display_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notification_preferences_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_preferences_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('notification_preferences_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_notification_preferences_id'), 'notification_preferences', ['id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('critical_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='آستانه بحرانی (Critical Threshold)'),
    sa.Column('warning_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='آستانه هشدار (Warning Threshold)'),
    sa.Column('access_token_expire_minutes', sa.INTEGER(), autoincrement=False, nullable=False, comment='مدت اعتبار Access Token (دقیقه)'),
    sa.Column('refresh_token_expire_days', sa.INTEGER(), autoincrement=False, nullable=False, comment='مدت اعتبار Refresh Token (روز)'),
    sa.Column('max_login_attempts', sa.INTEGER(), autoincrement=False, nullable=False, comment='حداکثر تلاش ناموفق ورود'),
    sa.Column('lockout_duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False, comment='مدت قفل شدن حساب (دقیقه)'),
    sa.Column('session_timeout_minutes', sa.INTEGER(), autoincrement=False, nullable=False, comment='Timeout نشست (دقیقه)'),
    sa.Column('polling_interval', sa.INTEGER(), autoincrement=False, nullable=False, comment='فاصله Polling (ثانیه)'),
    sa.Column('max_telemetry_failures', sa.INTEGER(), autoincrement=False, nullable=False, comment='حداکثر خطای مجاز تله\u200cمتری'),
    sa.Column('modbus_timeout', sa.INTEGER(), autoincrement=False, nullable=False, comment='Timeout Modbus (ثانیه)'),
    sa.Column('modbus_retry_count', sa.INTEGER(), autoincrement=False, nullable=False, comment='تعداد تلاش مجدد Modbus'),
    sa.Column('connection_pool_size', sa.INTEGER(), autoincrement=False, nullable=False, comment='اندازه Pool اتصالات'),
    sa.Column('data_retention_days', sa.INTEGER(), autoincrement=False, nullable=False, comment='مدت نگهداری داده\u200cهای تله\u200cمتری (روز)'),
    sa.Column('log_retention_days', sa.INTEGER(), autoincrement=False, nullable=False, comment='مدت نگهداری لاگ\u200cها (روز)'),
    sa.Column('audit_log_retention_days', sa.INTEGER(), autoincrement=False, nullable=False, comment='مدت نگهداری لاگ\u200cهای Audit (روز)'),
    sa.Column('notification_batch_size', sa.INTEGER(), autoincrement=False, nullable=False, comment='تعداد نوتیفیکیشن در هر Batch'),
    sa.Column('notification_retry_attempts', sa.INTEGER(), autoincrement=False, nullable=False, comment='تعداد تلاش مجدد نوتیفیکیشن'),
    sa.Column('notification_cooldown_seconds', sa.INTEGER(), autoincrement=False, nullable=False, comment='فاصله زمانی ارسال مجدد نوتیفیکیشن مشابه (ثانیه)'),
    sa.Column('report_generation_timeout', sa.INTEGER(), autoincrement=False, nullable=False, comment='Timeout تولید گزارش (ثانیه)'),
    sa.Column('max_export_records', sa.INTEGER(), autoincrement=False, nullable=False, comment='حداکثر رکورد در Export'),
    sa.Column('system_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='نام سیستم'),
    sa.Column('system_timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='منطقه زمانی'),
    sa.Column('maintenance_mode', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='وضعیت تعمیر و نگهداری'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('system_settings_pkey'))
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    # ### end Alembic commands ###
