"""add post_id and value_int to timeseries_data

Revision ID: db7af2ed1e20
Revises: d1651ca94c90
Create Date: 2026-08-20 12:51:13.820342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db7af2ed1e20'
down_revision: Union[str, Sequence[str], None] = 'd1651ca94c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeseries_data', sa.Column('post_id', sa.Integer(), nullable=True))
    op.add_column('timeseries_data', sa.Column('value_int', sa.Integer(), nullable=True))
    op.alter_column('timeseries_data', 'feeder_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('timeseries_data', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_foreign_key(None, 'timeseries_data', 'feeders', ['feeder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timeseries_data', type_='foreignkey')
    op.alter_column('timeseries_data', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('timeseries_data', 'feeder_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('timeseries_data', 'value_int')
    op.drop_column('timeseries_data', 'post_id')
    # ### end Alembic commands ###
