"""change phone_number

Revision ID: 23a8cdde770a
Revises: 3688a6e7527c
Create Date: 2026-08-17 10:54:06.742297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23a8cdde770a'
down_revision: Union[str, Sequence[str], None] = '3688a6e7527c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeseries_data_feeder_id'), table_name='timeseries_data')
    op.drop_index(op.f('ix_timeseries_data_id'), table_name='timeseries_data')
    op.drop_index(op.f('ix_timeseries_data_key'), table_name='timeseries_data')
    op.drop_index(op.f('ix_timeseries_data_timestamp'), table_name='timeseries_data')
    op.drop_table('timeseries_data')
    op.add_column('users', sa.Column('phone_number', sa.String(length=10), nullable=True))
    op.drop_index(op.f('ix_users_national_id'), table_name='users')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.drop_column('users', 'national_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('national_id', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_index(op.f('ix_users_national_id'), 'users', ['national_id'], unique=True)
    op.drop_column('users', 'phone_number')
    op.create_table('timeseries_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feeder_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('timeseries_data_pkey'))
    )
    op.create_index(op.f('ix_timeseries_data_timestamp'), 'timeseries_data', ['timestamp'], unique=False)
    op.create_index(op.f('ix_timeseries_data_key'), 'timeseries_data', ['key'], unique=False)
    op.create_index(op.f('ix_timeseries_data_id'), 'timeseries_data', ['id'], unique=False)
    op.create_index(op.f('ix_timeseries_data_feeder_id'), 'timeseries_data', ['feeder_id'], unique=False)
    # ### end Alembic commands ###
