"""add_device_models

Revision ID: 7ffb4626228c
Revises: aa466a7dc64a
Create Date: 2026-08-09 00:11:41.431286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ffb4626228c'
down_revision: Union[str, Sequence[str], None] = 'aa466a7dc64a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeders', sa.Column('modbus_address', sa.Integer(), nullable=True))
    op.add_column('feeders', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('feeders', sa.Column('last_success', sa.DateTime(), nullable=True))
    op.add_column('feeders', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('feeders', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index('idx_feeder_post', 'feeders', ['post_id'], unique=False)
    op.drop_constraint(op.f('feeders_post_id_fkey'), 'feeders', type_='foreignkey')
    op.create_foreign_key(None, 'feeders', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.add_column('links', sa.Column('length', sa.Float(), nullable=True))
    op.add_column('links', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('links', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('links', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('links', 'from_post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('links', 'to_post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('links_from_post_id_fkey'), 'links', type_='foreignkey')
    op.drop_constraint(op.f('links_to_post_id_fkey'), 'links', type_='foreignkey')
    op.create_foreign_key(None, 'links', 'posts', ['from_post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'links', 'posts', ['to_post_id'], ['id'], ondelete='CASCADE')
    op.add_column('locations', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('locations', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('locations', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('posts', sa.Column('port', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('posts', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('posts', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'posts', ['ip_address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_column('posts', 'updated_at')
    op.drop_column('posts', 'created_at')
    op.drop_column('posts', 'last_seen')
    op.drop_column('posts', 'metadata')
    op.drop_column('posts', 'port')
    op.drop_column('locations', 'updated_at')
    op.drop_column('locations', 'created_at')
    op.drop_column('locations', 'description')
    op.drop_constraint(None, 'links', type_='foreignkey')
    op.drop_constraint(None, 'links', type_='foreignkey')
    op.create_foreign_key(op.f('links_to_post_id_fkey'), 'links', 'posts', ['to_post_id'], ['id'])
    op.create_foreign_key(op.f('links_from_post_id_fkey'), 'links', 'posts', ['from_post_id'], ['id'])
    op.alter_column('links', 'to_post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('links', 'from_post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('links', 'updated_at')
    op.drop_column('links', 'created_at')
    op.drop_column('links', 'is_active')
    op.drop_column('links', 'length')
    op.drop_constraint(None, 'feeders', type_='foreignkey')
    op.create_foreign_key(op.f('feeders_post_id_fkey'), 'feeders', 'posts', ['post_id'], ['id'])
    op.drop_index('idx_feeder_post', table_name='feeders')
    op.drop_column('feeders', 'updated_at')
    op.drop_column('feeders', 'created_at')
    op.drop_column('feeders', 'last_success')
    op.drop_column('feeders', 'metadata')
    op.drop_column('feeders', 'modbus_address')
    # ### end Alembic commands ###
