"""add phone_number to users

Revision ID: b1b2083a6ef4
Revises: febec5eac43c
Create Date: 2026-08-16 13:30:15.149343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1b2083a6ef4'
down_revision: Union[str, Sequence[str], None] = 'febec5eac43c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeseries_data_feeder_id'), table_name='timeseries_data')
    op.drop_index(op.f('ix_timeseries_data_id'), table_name='timeseries_data')
    op.drop_index(op.f('ix_timeseries_data_key'), table_name='timeseries_data')
    op.drop_index(op.f('ix_timeseries_data_post_id'), table_name='timeseries_data')
    op.drop_index(op.f('ix_timeseries_data_timestamp'), table_name='timeseries_data')
    op.drop_table('timeseries_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeseries_data',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feeder_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value_int', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value_float', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('value_str', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('value_bool', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['feeder_id'], ['feeders.id'], name=op.f('timeseries_data_feeder_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('timeseries_data_post_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('timeseries_data_pkey'))
    )
    op.create_index(op.f('ix_timeseries_data_timestamp'), 'timeseries_data', ['timestamp'], unique=False)
    op.create_index(op.f('ix_timeseries_data_post_id'), 'timeseries_data', ['post_id'], unique=False)
    op.create_index(op.f('ix_timeseries_data_key'), 'timeseries_data', ['key'], unique=False)
    op.create_index(op.f('ix_timeseries_data_id'), 'timeseries_data', ['id'], unique=False)
    op.create_index(op.f('ix_timeseries_data_feeder_id'), 'timeseries_data', ['feeder_id'], unique=False)
    # ### end Alembic commands ###
