"""Make post_id and feeder_id nullable

Revision ID: febec5eac43c
Revises: 96228eb6683f
Create Date: 2026-08-10 16:54:32.617496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'febec5eac43c'
down_revision: Union[str, Sequence[str], None] = '96228eb6683f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeseries_data_feeder_id'), table_name='timeseries_data')
    op.drop_index(op.f('ix_timeseries_data_id'), table_name='timeseries_data')
    op.drop_index(op.f('ix_timeseries_data_key'), table_name='timeseries_data')
    op.drop_index(op.f('ix_timeseries_data_post_id'), table_name='timeseries_data')
    op.drop_index(op.f('ix_timeseries_data_timestamp'), table_name='timeseries_data')
    op.drop_table('timeseries_data')
    op.add_column('system_settings', sa.Column('refresh_token_expire_days', sa.Integer(), nullable=False, comment='مدت اعتبار Refresh Token (روز)'))
    op.add_column('system_settings', sa.Column('max_login_attempts', sa.Integer(), nullable=False, comment='حداکثر تلاش ناموفق ورود'))
    op.add_column('system_settings', sa.Column('lockout_duration_minutes', sa.Integer(), nullable=False, comment='مدت قفل شدن حساب (دقیقه)'))
    op.add_column('system_settings', sa.Column('session_timeout_minutes', sa.Integer(), nullable=False, comment='Timeout نشست (دقیقه)'))
    op.add_column('system_settings', sa.Column('modbus_timeout', sa.Integer(), nullable=False, comment='Timeout Modbus (ثانیه)'))
    op.add_column('system_settings', sa.Column('modbus_retry_count', sa.Integer(), nullable=False, comment='تعداد تلاش مجدد Modbus'))
    op.add_column('system_settings', sa.Column('connection_pool_size', sa.Integer(), nullable=False, comment='اندازه Pool اتصالات'))
    op.add_column('system_settings', sa.Column('data_retention_days', sa.Integer(), nullable=False, comment='مدت نگهداری داده\u200cهای تله\u200cمتری (روز)'))
    op.add_column('system_settings', sa.Column('log_retention_days', sa.Integer(), nullable=False, comment='مدت نگهداری لاگ\u200cها (روز)'))
    op.add_column('system_settings', sa.Column('audit_log_retention_days', sa.Integer(), nullable=False, comment='مدت نگهداری لاگ\u200cهای Audit (روز)'))
    op.add_column('system_settings', sa.Column('notification_batch_size', sa.Integer(), nullable=False, comment='تعداد نوتیفیکیشن در هر Batch'))
    op.add_column('system_settings', sa.Column('notification_retry_attempts', sa.Integer(), nullable=False, comment='تعداد تلاش مجدد نوتیفیکیشن'))
    op.add_column('system_settings', sa.Column('notification_cooldown_seconds', sa.Integer(), nullable=False, comment='فاصله زمانی ارسال مجدد نوتیفیکیشن مشابه (ثانیه)'))
    op.add_column('system_settings', sa.Column('report_generation_timeout', sa.Integer(), nullable=False, comment='Timeout تولید گزارش (ثانیه)'))
    op.add_column('system_settings', sa.Column('max_export_records', sa.Integer(), nullable=False, comment='حداکثر رکورد در Export'))
    op.add_column('system_settings', sa.Column('system_name', sa.String(length=100), nullable=False, comment='نام سیستم'))
    op.add_column('system_settings', sa.Column('system_timezone', sa.String(length=50), nullable=False, comment='منطقه زمانی'))
    op.add_column('system_settings', sa.Column('maintenance_mode', sa.Boolean(), nullable=False, comment='وضعیت تعمیر و نگهداری'))
    op.add_column('system_settings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('system_settings', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('system_settings', 'alfa',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='ضریب محاسباتی آلفا',
               existing_nullable=False)
    op.alter_column('system_settings', 'beta',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='ضریب محاسباتی بتا',
               existing_nullable=False)
    op.alter_column('system_settings', 'access_token_expire_minutes',
               existing_type=sa.INTEGER(),
               comment='مدت اعتبار Access Token (دقیقه)',
               existing_nullable=False)
    op.alter_column('system_settings', 'polling_interval',
               existing_type=sa.INTEGER(),
               comment='فاصله Polling (ثانیه)',
               existing_nullable=False)
    op.alter_column('system_settings', 'max_telemetry_failures',
               existing_type=sa.INTEGER(),
               comment='حداکثر خطای مجاز تله\u200cمتری',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_settings', 'max_telemetry_failures',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='حداکثر خطای مجاز تله\u200cمتری',
               existing_nullable=False)
    op.alter_column('system_settings', 'polling_interval',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='فاصله Polling (ثانیه)',
               existing_nullable=False)
    op.alter_column('system_settings', 'access_token_expire_minutes',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='مدت اعتبار Access Token (دقیقه)',
               existing_nullable=False)
    op.alter_column('system_settings', 'beta',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='ضریب محاسباتی بتا',
               existing_nullable=False)
    op.alter_column('system_settings', 'alfa',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='ضریب محاسباتی آلفا',
               existing_nullable=False)
    op.drop_column('system_settings', 'updated_at')
    op.drop_column('system_settings', 'created_at')
    op.drop_column('system_settings', 'maintenance_mode')
    op.drop_column('system_settings', 'system_timezone')
    op.drop_column('system_settings', 'system_name')
    op.drop_column('system_settings', 'max_export_records')
    op.drop_column('system_settings', 'report_generation_timeout')
    op.drop_column('system_settings', 'notification_cooldown_seconds')
    op.drop_column('system_settings', 'notification_retry_attempts')
    op.drop_column('system_settings', 'notification_batch_size')
    op.drop_column('system_settings', 'audit_log_retention_days')
    op.drop_column('system_settings', 'log_retention_days')
    op.drop_column('system_settings', 'data_retention_days')
    op.drop_column('system_settings', 'connection_pool_size')
    op.drop_column('system_settings', 'modbus_retry_count')
    op.drop_column('system_settings', 'modbus_timeout')
    op.drop_column('system_settings', 'session_timeout_minutes')
    op.drop_column('system_settings', 'lockout_duration_minutes')
    op.drop_column('system_settings', 'max_login_attempts')
    op.drop_column('system_settings', 'refresh_token_expire_days')
    op.create_table('timeseries_data',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feeder_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value_int', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value_float', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('value_str', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('value_bool', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['feeder_id'], ['feeders.id'], name=op.f('timeseries_data_feeder_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('timeseries_data_post_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('timeseries_data_pkey'))
    )
    op.create_index(op.f('ix_timeseries_data_timestamp'), 'timeseries_data', ['timestamp'], unique=False)
    op.create_index(op.f('ix_timeseries_data_post_id'), 'timeseries_data', ['post_id'], unique=False)
    op.create_index(op.f('ix_timeseries_data_key'), 'timeseries_data', ['key'], unique=False)
    op.create_index(op.f('ix_timeseries_data_id'), 'timeseries_data', ['id'], unique=False)
    op.create_index(op.f('ix_timeseries_data_feeder_id'), 'timeseries_data', ['feeder_id'], unique=False)
    # ### end Alembic commands ###
